---
version: 2
project_name: go-media-resizer

before:
  hooks:
    - go mod tidy

builds:
  - id: gmr
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - "-tags=nodynamic"
    ldflags:
      - " -s -w -X github.com/reflet-devops/go-media-resizer/version.Version={{.Tag}} -X github.com/reflet-devops/go-media-resizer/version.Commit={{.ShortCommit}}"
    binary: go-media-resizer
    env:
      - CGO_ENABLED=1
      - CC=gcc

dockers:
  - build_flag_templates:
      - "--platform=linux/arm64"
      - "--provenance=false"
      - "--build-arg=VERSION={{.Tag}}"
      - "--build-arg=COMMIT_SHORT={{.ShortCommit}}"
    dockerfile: Dockerfile
    goarch: arm64
    image_templates:
      - "refletdevops/go-media-resizer:v{{ .Version }}-arm64"
    use: buildx
    extra_files:
      - ./
  - build_flag_templates:
      - "--platform=linux/amd64"
      - "--provenance=false"
      - "--build-arg=VERSION={{.Tag}}"
      - "--build-arg=COMMIT_SHORT={{.ShortCommit}}"
    dockerfile: Dockerfile
    goarch: amd64
    image_templates:
      - "refletdevops/go-media-resizer:v{{ .Version }}-amd64"
    use: buildx
    extra_files:
      - ./

docker_manifests:
  - image_templates:
      - "refletdevops/go-media-resizer:v{{ .Version }}-arm64"
      - "refletdevops/go-media-resizer:v{{ .Version }}-amd64"
    name_template: "refletdevops/go-media-resizer:{{ .Tag }}"


archives:
  - id: gmr
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    ids:
      - gmr
    formats: ["binary"]

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
