name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: debian:13
    steps:
      - name: "Install dependencies"
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            git ca-certificates curl wget \
            libaom-dev libwebp-dev pkg-config gcc libc6-dev

      - name: Mark workspace as safe for git
        run: git config --global --add safe.directory '*'

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Get dependencies
        run: go mod download

      - name: Generate mock
        run: ./bin/mock.sh

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -tags=nodynamic -v -o go-media-resizer .

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: go-media-resizer
          path: go-media-resizer
          retention-days: 1
          if-no-files-found: error



